### ISSUE TITLE
strcmp(argc[1], "test")==0 does not compile (<cstring> not included)

### ISSUE THREAD

**Issue by ForrestBarnes** [ryanrouleau/Rouleau_CSCI2270_FinalProject#1]
Could be solved by adding an include cstring, but I believe it's just best to replace it with argc[1]=="test". Will send a pull request soon.

**Comment by ForrestBarnes** [comment]
By the way, this program does not compile on Windows. The curl library needs to be downloaded and the getpass function simply doesn't exist.

**Comment by ryanrouleau** [comment]
Since argc[1] returns a char array, if you compare to a string literal like "test," the comparison is unpredictable.  In this case, it will always evaluate as false.  strcmp() compares the two different types of strings; however, I didn't know that <cstring> was required to use it as it always worked for me.  Anyways, I'll add that fix.  Also thank you for testing it on Windows!

**Comment by ryanrouleau** [comment]
Fixed.
